### ISSUE TITLE
Auto language detection improvements

### ISSUE THREAD

**Issue by ajmath** [sous-chefs/language-chef#4]
How can we make the auto-detection better so that Atom can know when a .rb should be used with the Chef language?

**Comment by hd-deman** [comment]
I fix it via [file-types](https://atom.io/packages/file-types) and [project-manager](https://atom.io/packages/project-manager) packages.
```cson
# projects.cson
'some-rails-project':
  'title': 'some-rails-project'
  'template': 'rails-template'

'some-cookbook':
  'title': 'some-cookbook'
  'template': 'chef-cookbook'

'chef-template':
  'icon': 'icon-coffeescript'
  'settings':
    'file-types':
      'rb': 'source.ruby.chef'

'rails-template':
  'icon': 'icon-coffeescript'
  'settings':
    'file-types':
      'rb': 'source.ruby.rails'
```

**Comment by kidbrax** [comment]
Yeah, can't really use this if it thinks every ruby file is chef.

**Comment by pschaumburg** [comment]
Closed issue, as whole package received nearly complete redesign.
